### ISSUE TITLE
USER STORY: Vote anonymously to maintain privacy

### ISSUE THREAD

**Issue by alicehillier** [alicehillier/My-First-Agile-Project#4]
As a **user**, I can **vote anonymously** so that **I can maintain my privacy**.

# Acceptance Criteria:

- Acceptance Criteria 1: The option to vote anonymously must be clearly displayed to the user.
- Acceptance Criteria 2: Instead of showing the user's profile picture, a default anonymous profile picture should be shown.
- Acceptance Criteria 3: The user must be informed that posting anonymously will hide their name, picture and profile.

# Tasks:

- [ ] Task 1: Create a 'vote anonymously' button.
- [ ] Task 2: Design the anonymous profile image.
- [ ] Task 3: Create the code to enable and carry out anonymous voting.
