### ISSUE TITLE
USER STORY: Changing website colour scheme without code.

### ISSUE THREAD

**Issue by alicehillier** [alicehillier/My-First-Agile-Project#5]
As a **UX Designer**, I can **customise my website's colour scheme without code** so that **I can create my designs more efficiently and easily**.

# Acceptance Criteria:

- Acceptance Criteria 1: The user must be able to click on a colour to change the element's appearance. 
- Acceptance Criteria 2: A wide range of colours must be available to the user. 
- Acceptance Criteria 3: All elements must be customisable.

# Tasks:

- [ ] Task 1: Select a set of HTML elements that the user can customise.
- [ ] Task 2: Design a colour selector tool and link it to each element in the set.
- [ ] Task 3: Create the user interface where the user can click on their desired colour, which changes the element's appearance when it's clicked on.
